# Generated by Django 3.1.5 on 2021-03-17 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_invoiceline_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['name'], 'verbose_name': 'Customer', 'verbose_name_plural': 'Customers'},
        ),
    ]
